### PR TITLE
Master

### PR DESCRIPTION
**Pull request by PiotrZub**
Add nativePath for some function to make it more compatible with java
port.

### CODE REVIEW

**Comment by FabricioCabeca** [comment]
Thanks !

**Comment by FabricioCabeca** [comment]
Just to let you know, we will revert the LocalCacheFolder line in our next commit. Also, we didn't get the need for the recursive replace as the method already replaces all matches.

**Comment by PiotrZub** [comment]
Thanks for information.
Why you prefer LocalCacheFolder? 
How I understand the LocalCacheFolder is not backuped so user can loss program configuration?
Another problem is that I do not know any PC tools to browse LocalCacheFolder. Only local,remote and temporary folders are shown.
I think in future all filesystems (local,remote,temporary,sdcard..)  should be exposed to for java as file://local/ or file://sdcard/.

"we didn't get the need for the recursive replace as the method already replaces all matches."
about which function your write?

**Comment by FabricioCabeca** [comment]
Yes, LocalCacheFolder is not backuped, and due to this performance is greatly improved. You are right about the possibility to be able to access all folders, user preferences may benefit from cloud backup, but cached images are way slower when stored the same way, right now performance is my main concern.

This is what I've mentioned:

```
+            {
-                ss = ss.Substring(6).Replace('/', '\\');
+                ss = ss.Substring(6);
+                while (ss[0] == '/')
+                {
+                    ss = ss.Substring(1);
+                }
+                ss = ss.Replace('/', '\\');
```

but as I told you we weren't using it yet, so it is probably right

**Pull request merged**
